/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":luaj-core"))
    api(project(":luaj-jme"))
    api(project(":luaj-jse"))
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.microemu.microemulator)
    testImplementation(libs.org.microemu.microemu.jsr.v75)
    testRuntimeOnly(libs.org.junit.platform.launcher)
}

sourceSets {
    test {
        java.srcDir("src/test/java")
    }
}

tasks.test {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
    }
}
description = "LuaJ-Tests"
