/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":luaj-core"))
    api(libs.org.apache.bcel.bcel)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testRuntimeOnly(libs.org.junit.platform.launcher)
    compileOnly(libs.com.github.mcpat.apistubs.cldc.v1.v1.stub)
}

description = "luaj-jme"
