/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":luaj-core"))
    api(libs.org.apache.bcel.bcel)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
}

description = "luaj-jse"

val generateGrammar by tasks.registering(JavaExec::class) {
    val inputDir = file("src/main/javacc")
    val outputDir = layout.buildDirectory.dir("generated-sources/javacc").get().asFile

    inputs.dir(inputDir)
    outputs.dir(outputDir)

    classpath = configurations.detachedConfiguration(
        dependencies.create("net.java.dev.javacc:javacc:7.0.13")
    )
    mainClass.set("org.javacc.parser.Main")

    doFirst {
        outputDir.mkdirs()
        args = listOf(
            file("src/main/javacc/LuaParser.jj").absolutePath
        )
    }

    notCompatibleWithConfigurationCache("JavaExec with doFirst args")
}

sourceSets.main {
    java.srcDir("src/jse")
}

tasks.compileJava {
    dependsOn(generateGrammar)
}
